#!/usr/bin/env bash

alias ls="eza --icons --color=always --group-directories-first"

# alias ls="eza -la --icons --color=always --group-directories-first"
# alias la="eza -a --icons --color=always --group-directories-first"
# alias ll="eza -l --icons --color=always --group-directories-first"
# alias lt="eza -aT --icons --color=always --group-directories-first"

alias emacs="emacsclient --create-frame --alternate-editor='emacs'"
# alias n="neovide.exe --wsl"
