#!/usr/bin/env bash

alias cat="bat"
alias grep="rg"
alias ls="exa --icons"
alias emacs="emacsclient --create-frame --alternate-editor='emacs'"
# alias n="neovide.exe --wsl"

# alias luamake=/luamake
alias luamake=/home/blazkowolf/.local/share/nvim/lsp_servers/lua-language-server/3rd/luamake/luamake
